import { Baloo_Da_2 ,  Fira_Code } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";

const balooda = Baloo_Da_2({ subsets: ["latin"], display: "swap" });
const fira = Fira_Code({subsets : ["latin"]})

export const metadata = {
  title: "First Next Js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log('hello');
  return (
    <html lang="en">
      <body className={fira.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
